// MIFARE CLASSIC Authentication Modes:
const MIFARE_AUTHENTICATION={
	MIFARE_AUTHENT1A : 0x60,
	MIFARE_AUTHENT1B : 0x61,
};

//MIFARE PLUS AES Authentication Modes:
const MIFARE_PLUS_AES_AUTHENTICATION={
	MIFARE_PLUS_AES_AUTHENT1A : 0x80,
	MIFARE_PLUS_AES_AUTHENT1B : 0x81,
};

// T2T authentication constants: NTAG/Ultralight
const T2T_AUTHENTICATION={
	T2T_NO_PWD_AUTH	: 0,
	T2T_RKA_PWD_AUTH : 1,
	T2T_PK_PWD_AUTH : 3,
	T2T_WITHOUT_PWD_AUTH : 0x60,
	T2T_WITH_PWD_AUTH : 0x61,
};

const ADDRESS_MODE={
	ADDRESS_MODE_BLOCK :0,
	ADDRESS_MODE_SECTOR :1,
};


const UFCODER_ERROR_CODES ={
	UFR_OK : 0x00,
	UFR_COMMUNICATION_ERROR : 0x01,
	UFR_CHKSUM_ERROR : 0x02,
	UFR_READING_ERROR : 0x03,
	UFR_WRITING_ERROR : 0x04,
	UFR_BUFFER_OVERFLOW : 0x05,
	UFR_MAX_ADDRESS_EXCEEDED : 0x06,
	UFR_MAX_KEY_INDEX_EXCEEDED : 0x07,
	UFR_NO_CARD : 0x08,
	UFR_COMMAND_NOT_SUPPORTED : 0x09,
	UFR_FORBIDEN_DIRECT_WRITE_IN_SECTOR_TRAILER : 0x0A,
	UFR_ADDRESSED_BLOCK_IS_NOT_SECTOR_TRAILER : 0x0B,
	UFR_WRONG_ADDRESS_MODE : 0x0C,
	UFR_WRONG_ACCESS_BITS_VALUES : 0x0D,
	UFR_AUTH_ERROR : 0x0E,
	UFR_PARAMETERS_ERROR : 0x0F, // ToDo, point 5.
	UFR_MAX_SIZE_EXCEEDED : 0x10,
	UFR_UNSUPPORTED_CARD_TYPE : 0x11,

	UFR_COMMUNICATION_BREAK : 0x50,
	UFR_NO_MEMORY_ERROR : 0x51,
	UFR_CAN_NOT_OPEN_READER : 0x52,
	UFR_READER_NOT_SUPPORTED : 0x53,
	UFR_READER_OPENING_ERROR : 0x54,
	UFR_READER_PORT_NOT_OPENED : 0x55,
	UFR_CANT_CLOSE_READER_PORT : 0x56,

	UFR_WRITE_VERIFICATION_ERROR : 0x70,
	UFR_BUFFER_SIZE_EXCEEDED : 0x71,
	UFR_VALUE_BLOCK_INVALID : 0x72,
	UFR_VALUE_BLOCK_ADDR_INVALID : 0x73,
	UFR_VALUE_BLOCK_MANIPULATION_ERROR : 0x74,
	UFR_WRONG_UI_MODE : 0x75,
	UFR_KEYS_LOCKED : 0x76,
	UFR_KEYS_UNLOCKED : 0x77,
	UFR_WRONG_PASSWORD : 0x78,
	UFR_CAN_NOT_LOCK_DEVICE : 0x79,
	UFR_CAN_NOT_UNLOCK_DEVICE : 0x7A,
	UFR_DEVICE_EEPROM_BUSY : 0x7B,
	UFR_RTC_SET_ERROR : 0x7C,

	ANTI_COLLISION_DISABLED : 0x7D,
	NO_TAGS_ENUMERRATED : 0x7E,
	CARD_ALREADY_SELECTED : 0x7F,

	// NDEF error codes
	UFR_WRONG_NDEF_CARD_FORMAT : 0x80,
	UFR_NDEF_MESSAGE_NOT_FOUND : 0x81,
	UFR_NDEF_UNSUPPORTED_CARD_TYPE : 0x82,
	UFR_NDEF_CARD_FORMAT_ERROR : 0x83,
	UFR_MAD_NOT_ENABLED : 0x84,
	UFR_MAD_VERSION_NOT_SUPPORTED : 0x85,
    UFR_NDEF_MESSAGE_NOT_COMPATIBLE : 0x86,

	// Tag emulation mode errors:
	FORBIDDEN_IN_TAG_EMULATION_MODE : 0x90,

	// FTDI errors:
	UFR_FT_STATUS_ERROR_1 : 0xA0,
	UFR_FT_STATUS_ERROR_2 : 0xA1,
	UFR_FT_STATUS_ERROR_3 : 0xA2,
	UFR_FT_STATUS_ERROR_4 : 0xA3,
	UFR_FT_STATUS_ERROR_5 : 0xA4,
	UFR_FT_STATUS_ERROR_6 : 0xA5,
	UFR_FT_STATUS_ERROR_7 : 0xA6,
	UFR_FT_STATUS_ERROR_8 : 0xA7,
	UFR_FT_STATUS_ERROR_9 : 0xA8,

	//MIFARE PLUS error codes
	UFR_MFP_COMMAND_OVERFLOW : 0xB0,
	UFR_MFP_INVALID_MAC : 0xB1,
	UFR_MFP_INVALID_BLOCK_NR : 0xB2,
	UFR_MFP_NOT_EXIST_BLOCK_NR : 0xB3,
	UFR_MFP_COND_OF_USE_ERROR :	0xB4,
	UFR_MFP_LENGTH_ERROR : 	0xB5,
	UFR_MFP_GENERAL_MANIP_ERROR : 0xB6,
	UFR_MFP_SWITCH_TO_ISO14443_4_ERROR : 0xB7,
	UFR_MFP_ILLEGAL_STATUS_CODE : 0xB8,
	UFR_MFP_MULTI_BLOCKS_READ : 0xB9,

	// multiple units - return from the functions with ReaderList_ prefix in name
	UFR_DEVICE_WRONG_HANDLE : 0x100,
	UFR_DEVICE_INDEX_OUT_OF_BOUND: 0x101,
	UFR_DEVICE_ALREADY_OPENED: 0x102,
	UFR_DEVICE_ALREADY_CLOSED: 0x103,
	UFR_DEVICE_IS_NOT_CONNECTED:  0x104,

	// Originality Check Error Codes:
	UFR_NOT_NXP_GENUINE : 0x200,
	UFR_OPEN_SSL_DYNAMIC_LIB_FAILED: 0x201,
	UFR_OPEN_SSL_DYNAMIC_LIB_NOT_FOUND:  0x202,

	// DESFIRE Card Status Error Codes:
	READER_ERROR : 0xBB7,					// 2999 [dec]
	NO_CARD_DETECTED : 0xBB8,				// 3000 [dec]
	CARD_OPERATION_OK : 0xBB9,				// 3001 [dec]
	WRONG_KEY_TYPE : 0xBBA,					// 3002 [dec]
	KEY_AUTH_ERROR : 0xBBB,					// 3003 [dec]
	CARD_CRYPTO_ERROR : 0xBBC,				// 3004 [dec]
	READER_CARD_COMM_ERROR : 0xBBD,			// 3005 [dec]
	PC_READER_COMM_ERROR : 0xBBE,			// 3006 [dec]
	COMMIT_TRANSACTION_NO_REPLY : 0xBBF,	// 3007 [dec]
	COMMIT_TRANSACTION_ERROR : 0xBC0,		// 3008 [dec]
	NOT_SUPPORTED_KEY_TYPE : 0xBC2,			// 3010 [dec]

	DESFIRE_CARD_NO_CHANGES : 0x0C0C,
	DESFIRE_CARD_OUT_OF_EEPROM_ERROR : 0x0C0E,
	DESFIRE_CARD_ILLEGAL_COMMAND_CODE : 0x0C1C,
	DESFIRE_CARD_INTEGRITY_ERROR : 0x0C1E,
	DESFIRE_CARD_NO_SUCH_KEY : 0x0C40,
	DESFIRE_CARD_LENGTH_ERROR : 0x0C7E,
	DESFIRE_CARD_PERMISSION_DENIED : 0x0C9D,
	DESFIRE_CARD_PARAMETER_ERROR : 0x0C9E,
	DESFIRE_CARD_APPLICATION_NOT_FOUND : 0x0CA0,
	DESFIRE_CARD_APPL_INTEGRITY_ERROR : 0x0CA1,
	DESFIRE_CARD_AUTHENTICATION_ERROR : 0x0CAE,
	DESFIRE_CARD_ADDITIONAL_FRAME : 0x0CAF,
	DESFIRE_CARD_BOUNDARY_ERROR : 0x0CBE,
	DESFIRE_CARD_PICC_INTEGRITY_ERROR : 0x0CC1,
	DESFIRE_CARD_COMMAND_ABORTED : 0x0CCA,
	DESFIRE_CARD_PICC_DISABLED_ERROR : 0x0CCD,
	DESFIRE_CARD_COUNT_ERROR : 0x0CCE,
	DESFIRE_CARD_DUPLICATE_ERROR : 0x0CDE,
	DESFIRE_CARD_EEPROM_ERROR_DES : 0x0CEE,
	DESFIRE_CARD_FILE_NOT_FOUND : 0x0CF0,
	DESFIRE_CARD_FILE_INTEGRITY_ERROR : 0x0CF1,

	// uFCoder library errors:
	UFR_NOT_IMPLEMENTED : 0x1000,
	UFR_COMMAND_FAILED : 0x1001,
	UFR_TIMEOUT_ERR : 0x1002,
	UFR_FILE_SYSTEM_ERROR : 0x1003,
	UFR_FILE_SYSTEM_PATH_NOT_EXISTS : 0x1004,
	UFR_FILE_NOT_EXISTS : 0x1005,

	// JC cards APDU Error Codes:
	UFR_APDU_TRANSCEIVE_ERROR : 0xAE,
	UFR_APDU_JC_APP_NOT_SELECTED  : 0x6000,
	UFR_APDU_JC_APP_BUFF_EMPTY : 0x6001,
	UFR_APDU_WRONG_SELECT_RESPONSE : 0x6002,
	UFR_APDU_WRONG_KEY_TYPE : 0x6003,
	UFR_APDU_WRONG_KEY_SIZE : 0x6004,
	UFR_APDU_WRONG_KEY_PARAMS : 0x6005,
	UFR_APDU_WRONG_SIGNING_ALGORITHM : 0x6006,
	UFR_APDU_PLAIN_TEXT_MAX_SIZE_EXCEEDED : 0x6007,
	UFR_APDU_UNSUPPORTED_KEY_SIZE : 0x6008,
	UFR_APDU_UNSUPPORTED_ALGORITHMS : 0x6009,
	UFR_APDU_PKI_OBJECT_NOT_FOUND : 0x600A,
	UFR_APDU_MAX_PIN_LENGTH_EXCEEDED : 0x600B,
	UFR_DIGEST_LENGTH_DOES_NOT_MATCH : 0x600C,

	// Secure channel specific errors:
	UFR_SECURE_CHANNEL_SESSION_FAILED : 0x6C00,

	// ISO7816-4 Errors (R-APDU) - 2 SW bytes returned by the card, prefixed with 0x000A:
	UFR_APDU_SW_TAG : 0x000A0000,
	UFR_APDU_SW_WRONG_LENGTH : 0x000A6700,
	UFR_APDU_SW_SECURITY_STATUS_NOT_SATISFIED : 0x000A6982,
	UFR_APDU_SW_AUTHENTICATION_METHOD_BLOCKED : 0x000A6983,
	UFR_APDU_SW_DATA_INVALID : 0x000A6984,
	UFR_APDU_SW_CONDITIONS_NOT_SATISFIED : 0x000A6985,
	UFR_APDU_SW_WRONG_DATA : 0x000A6A80,
	UFR_APDU_SW_FILE_NOT_FOUND : 0x000A6A82,
	UFR_APDU_SW_RECORD_NOT_FOUND : 0x000A6A83,
	UFR_APDU_SW_DATA_NOT_FOUND : 0x000A6A88,
	UFR_APDU_SW_ENTITY_ALREADY_EXISTS : 0x000A6A89,
	UFR_APDU_SW_INS_NOT_SUPPORTED : 0x000A6D00,
	UFR_APDU_SW_NO_PRECISE_DIAGNOSTIC : 0x000A6F00,
	//SAM module error codes:
	UFR_SAM_APDU_ERROR : 0x2000,
	UFR_SAM_AUTH_ERROR : 0x2001,
	UFR_SAM_CRYPTO_ERROR: 0x2002,

	MAX_UFR_STATUS : 0x7FFFFFFF
}


module.exports.DEFAULT_KEY = new Buffer.from([0xFF,0xFF,0xFF,0xFF,0xFF,0xFF]);

module.exports.STATUS=UFCODER_ERROR_CODES;
module.exports.MIFARE_AUTHENTICATION=MIFARE_AUTHENTICATION;
module.exports.MIFARE_PLUS_AES_AUTHENTICATION=MIFARE_PLUS_AES_AUTHENTICATION;
module.exports.T2T_AUTHENTICATION=T2T_AUTHENTICATION;
module.exports.ADDRESS_MODE=ADDRESS_MODE;